<a href="https://colab.research.google.com/github/kartik580/pandas-data-frame-/blob/main/pandas_DATAFRAME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=[
    ["Kartik", 23, "Male", "Data Science", 89],
    ["Rahul", 21, "Male", "Python", 76],
    ["Priya", 22, "Female", "Machine Learning", 92],
    ["Aman", 24, "Male", "Data Analytics", 81],
    ["Neha", 20, "Female", "Artificial Intelligence", 95],
    ["Rohit", 23, "Male", "Web Development", 74],
    ["Sneha", 21, "Female", "Data Science", 88],
    ["Vikas", 25, "Male", "Cyber Security", 79],
    ["Anjali", 22, "Female", "Python", 91],
    ["Arjun", 23, "Male", "Machine Learning", 85],
    ["Pooja", 21, "Female", "Data Analytics", 87],
    ["Mohit", 24, "Male", "Artificial Intelligence", 82],
    ["Kavya", 20, "Female", "Data Science", 94],
    ["Sahil", 22, "Male", "Python", 78],
    ["Riya", 23, "Female", "Machine Learning", 90]
]
columns= ["name","age","gender","course","marks"]
students=pd.DataFrame(data,columns=columns)
students

      name  age  gender                   course  marks
0   Kartik   23    Male             Data Science     89
1    Rahul   21    Male                   Python     76
2    Priya   22  Female         Machine Learning     92
3     Aman   24    Male           Data Analytics     81
4     Neha   20  Female  Artificial Intelligence     95
5    Rohit   23    Male          Web Development     74
6    Sneha   21  Female             Data Science     88
7    Vikas   25    Male           Cyber Security     79
8   Anjali   22  Female                   Python     91
9    Arjun   23    Male         Machine Learning     85
10   Pooja   21  Female           Data Analytics     87
11   Mohit   24    Male  Artificial Intelligence     82
12   Kavya   20  Female             Data Science     94
13   Sahil   22    Male                   Python     78
14    Riya   23  Female         Machine Learning     90

In [ ]:
students.head()

     name  age  gender                   course  marks
0  Kartik   23    Male             Data Science     89
1   Rahul   21    Male                   Python     76
2   Priya   22  Female         Machine Learning     92
3    Aman   24    Male           Data Analytics     81
4    Neha   20  Female  Artificial Intelligence     95

In [ ]:
data = {
    "name": [
        "Kartik", "Rahul", "Priya", "Aman", "Neha",
        "Rohit", "Sneha", "Vikas", "Anjali", "Arjun",
        "Pooja", "Mohit", "Kavya", "Sahil", "Riya"
    ],

    "age": [
        23, 21, 22, 24, 20,
        23, 21, 25, 22, 23,
        21, 24, 20, 22, 23
    ],

    "gender": [
        "Male", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "course": [
        "Data Science", "Python", "Machine Learning", "Data Analytics",
        "Artificial Intelligence", "Web Development", "Data Science",
        "Cyber Security", "Python", "Machine Learning",
        "Data Analytics", "Artificial Intelligence", "Data Science",
        "Python", "Machine Learning"
    ],

    "marks": [
        89, 76, 92, 81, 95,
        74, 88, 79, 91, 85,
        87, 82, 94, 78, 90
    ]
}
students=pd.DataFrame(data)
students

      name  age  gender                   course  marks
0   Kartik   23    Male             Data Science     89
1    Rahul   21    Male                   Python     76
2    Priya   22  Female         Machine Learning     92
3     Aman   24    Male           Data Analytics     81
4     Neha   20  Female  Artificial Intelligence     95
5    Rohit   23    Male          Web Development     74
6    Sneha   21  Female             Data Science     88
7    Vikas   25    Male           Cyber Security     79
8   Anjali   22  Female                   Python     91
9    Arjun   23    Male         Machine Learning     85
10   Pooja   21  Female           Data Analytics     87
11   Mohit   24    Male  Artificial Intelligence     82
12   Kavya   20  Female             Data Science     94
13   Sahil   22    Male                   Python     78
14    Riya   23  Female         Machine Learning     90

In [ ]:
students.head()

     name  age  gender                   course  marks
0  Kartik   23    Male             Data Science     89
1   Rahul   21    Male                   Python     76
2   Priya   22  Female         Machine Learning     92
3    Aman   24    Male           Data Analytics     81
4    Neha   20  Female  Artificial Intelligence     95

In [ ]:
students.tail()

     name  age  gender                   course  marks
10  Pooja   21  Female           Data Analytics     87
11  Mohit   24    Male  Artificial Intelligence     82
12  Kavya   20  Female             Data Science     94
13  Sahil   22    Male                   Python     78
14   Riya   23  Female         Machine Learning     90

In [ ]:
students.shape

(15, 5)

In [ ]:
students.columns

Index(['name', 'age', 'gender', 'course', 'marks'], dtype='object')

In [ ]:
type(students.columns)

pandas.core.indexes.base.Index

In [ ]:
students.columns.to_list()

['name', 'age', 'gender', 'course', 'marks']

In [ ]:
students.index

RangeIndex(start=0, stop=15, step=1)

In [ ]:
students.dtypes

name      object
age        int64
gender    object
course    object
marks      int64
dtype: object

In [ ]:
students.size

75

In [ ]:
students.head(10)

     name  age  gender                   course  marks
0  Kartik   23    Male             Data Science     89
1   Rahul   21    Male                   Python     76
2   Priya   22  Female         Machine Learning     92
3    Aman   24    Male           Data Analytics     81
4    Neha   20  Female  Artificial Intelligence     95
5   Rohit   23    Male          Web Development     74
6   Sneha   21  Female             Data Science     88
7   Vikas   25    Male           Cyber Security     79
8  Anjali   22  Female                   Python     91
9   Arjun   23    Male         Machine Learning     85

In [ ]:
students.tail(10)

      name  age  gender                   course  marks
5    Rohit   23    Male          Web Development     74
6    Sneha   21  Female             Data Science     88
7    Vikas   25    Male           Cyber Security     79
8   Anjali   22  Female                   Python     91
9    Arjun   23    Male         Machine Learning     85
10   Pooja   21  Female           Data Analytics     87
11   Mohit   24    Male  Artificial Intelligence     82
12   Kavya   20  Female             Data Science     94
13   Sahil   22    Male                   Python     78
14    Riya   23  Female         Machine Learning     90

In [ ]:
students.shape[0] #rows

15

In [ ]:
students.shape[1]# columns

5

In [ ]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    15 non-null     object
 1   age     15 non-null     int64
 2   gender  15 non-null     object
 3   course  15 non-null     object
 4   marks   15 non-null     int64
dtypes: int64(2), object(3)
memory usage: 732.0+ bytes

In [ ]:
students.describe()

             age      marks
count  15.000000  15.000000
mean   22.266667  85.400000
std     1.486447   6.706074
min    20.000000  74.000000
25%    21.000000  80.000000
50%    22.000000  87.000000
75%    23.000000  90.500000
max    25.000000  95.000000